### ISSUE TITLE
.env jangan langsung diupload

### ISSUE THREAD

**Issue by afikrim** [muhajirmuhajir/room-loan#1]
.env jangan diupload muhajir. Mending kamu bikin .env.example terus nanti dikosongin buat database dan secretnya. Soalnya kalo kredensial database dan secret key kamu upload juga, nanti semua orang bisa akses databasemu dan bisa dekripsi jwtmu.

**Comment by muhajirmuhajir** [comment]
Oiya makasih ziz, awalnya repoku ini ku private. Pas setting public lupa di gitignore

**Comment by afikrim** [comment]
woke mantap mantap
